spring.application.name=studentSpring
spring.mongodb.uri=mongodb+srv://food_delivery:food_delivery_password@cluster0.0mfbzbi.mongodb.net/student_management?retryWrites=true&w=majority&appName=Cluster0
server.port=${PORT:8080}